# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [5]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin PC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin PC/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin PC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin PC/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin PC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin PC/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin PC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin PC/anaconda3\\Library\\include']
Supported SIMD extens

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [6]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [13]:
a=np.array([100,200,300])
print("No. of elements:",a.size)
print("Memory size of one array element in bytes",a.itemsize)
print("Total Memory size of an array:",(a.size)*(a.itemsize)) 


No. of elements: 3
Memory size of one array element in bytes 4
Total Memory size of an array: 12


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [40]:

np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [19]:
null=np.zeros(10)
null[4]=1
print(null,type(null))

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] <class 'numpy.ndarray'>


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [16]:
a=np.arange(10,49)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


numpy.ndarray

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [30]:
a=np.arange(1,10)
a=a[::-1]
print(a)

[9 8 7 6 5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [24]:
a=np.arange(0,9)
a=np.reshape(a,(3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [68]:
a=np.array([1,2,0,0,4.0])
print(np.nonzero(a))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [109]:
a=np.eye(3,dtype=int) #using np.eye(No. of rows/coulumns)
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [73]:
a=np.identity(3,dtype=int) #using np.identity
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [77]:
a=np.random.random((3,3,3))
a

array([[[0.73888679, 0.06467254, 0.23142014],
        [0.7370188 , 0.20911951, 0.17770373],
        [0.75870421, 0.70951693, 0.84366672]],

       [[0.99909478, 0.70777279, 0.04915727],
        [0.67988705, 0.84045794, 0.98767883],
        [0.17534706, 0.90256019, 0.52580449]],

       [[0.18104145, 0.47677952, 0.33839748],
        [0.83191489, 0.08672239, 0.21046901],
        [0.58538586, 0.14594619, 0.26346602]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 

(**hint**: min, max)

In [70]:

a=np.random.random((10,10)) #random.random((shape of 2D array))         It returns float values
                             # random.random(high,low,size)--> general
print(a)
minimum=np.min(a)
maximum=np.max(a)
print(maximum,minimum)

[[0.67714708 0.59121853 0.45783064 0.62807516 0.0755368  0.36929693
  0.53782591 0.26608538 0.38681669 0.89223927]
 [0.6073731  0.55886178 0.04138419 0.67857948 0.99442919 0.9654094
  0.57373113 0.11834808 0.94507913 0.48129687]
 [0.4211056  0.80837662 0.16847209 0.36165855 0.20825436 0.94872519
  0.73131262 0.66617205 0.54778974 0.76589951]
 [0.54720267 0.90176127 0.66277025 0.02113858 0.03443065 0.7270055
  0.92739672 0.06299255 0.37421951 0.44775886]
 [0.41345998 0.77266871 0.14834672 0.08604331 0.35941878 0.10715804
  0.00975805 0.92220349 0.48214124 0.10320672]
 [0.85726751 0.85666547 0.60035012 0.93626008 0.72834693 0.33934466
  0.37211689 0.95180466 0.1807899  0.43491069]
 [0.11616684 0.95133612 0.73342902 0.88362155 0.64101884 0.03937914
  0.65712852 0.84918428 0.52830961 0.4900103 ]
 [0.31646976 0.552506   0.28195562 0.78198876 0.04509582 0.28887957
  0.61506333 0.35195372 0.61545047 0.03318893]
 [0.39588766 0.1806049  0.99322562 0.40310982 0.13639252 0.94009642
  0.70980461 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [98]:
a=np.random.randint(0,100,size=30) #Random integer values in range of (0,100) with size/count=30 samples
print("Random Vector Array:",a)
print("Mean of random vector",np.mean(a))

Random Vector Array: [26 60 38  7 16 49 63 73 66 53 31 35 86 97 23 63 44 89 26 71 65 84 51 64
 89  9 91 45 85  7]
Mean of random vector 53.53333333333333


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [112]:
a=np.ones((4,4),dtype=int)
a[1:-1,1:-1]=0 # for accessing the central part(central rows,central columns) 
a

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [188]:
a=np.random.randint(0,100,size=(3,3))
a1=np.pad(a,pad_width=1,mode="constant",constant_values=0) # for adding 0's around the array like border
print("Original array")
print(a)
print("Zero border added array:")
print(a1)

Original array
[[36 14 75]
 [56 85  5]
 [42 15 43]]
Zero border added array:
[[ 0  0  0  0  0]
 [ 0 36 14 75  0]
 [ 0 56 85  5  0]
 [ 0 42 15 43  0]
 [ 0  0  0  0  0]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [186]:

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [194]:

a=np.diag((1,2,3,4))
a=np.pad(a,1) #padding the diagonal matrix with 0
a=a[0:-1,1:] # Removing the 1st column and last row of padded array to get result
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [192]:

a=np.diag([1,2,3,4],k=-1) # Here k refers to above/below main diagonal 
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [185]:
a=np.zeros((8,8),dtype=int)
a[::2,::2]=1
a[1::2,1::2]=1 # For converting into checkboard pattern
a



array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [213]:

print(np.unravel_index(100,(6,7,8))) # It unravels the 3d index of flattend 100 th element of the array
#100-->flattened index to unravel;(6,7,8)--> shape of the array

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [226]:
a=np.array([[1,0],[0,1]])
print("Array")
print(a)
print("Array after tile")
a=np.tile(a,(4,4))
print(a)

Array
[[1 0]
 [0 1]]
Array after tile
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [234]:
a=np.random.randint(0,50,(5,5))
a1=(a-a.min())/(a.max()-a.min())
print(a1)

[[0.         0.14583333 0.79166667 0.4375     0.1875    ]
 [0.22916667 0.6875     0.04166667 0.35416667 0.22916667]
 [0.41666667 0.08333333 0.5        1.         0.8125    ]
 [0.02083333 0.83333333 0.3125     0.125      0.625     ]
 [0.1875     0.8125     0.6875     0.91666667 0.97916667]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [5]:
import numpy as np 
color=np.dtype([ ("r",np.ubyte,1),
                 ("g",np.ubyte,1),
                 ("b",np.ubyte,1),
                 ("a",np.ubyte,1)])

C:\Users\Admin PC\AppData\Local\Temp\ipykernel_14952\3607463953.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color=np.dtype([ ("r",np.ubyte,1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [3]:
import numpy as np
a=np.dot(np.arange(15).reshape((5,3)),np.arange(6).reshape(3,2))
b=np.arange(15).reshape((5,3))@np.arange(6).reshape((3,2)) # Another method for product
print(a)
print(b)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [39]:
x = np.arange(10)
x[(3 < x) & (x <= 8)] *=-1
print(x)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [4]:

print(sum(range(5),-1)) # Here it refers to minus 1 of the ans of range(5)
import numpy as np 
print(np.sum(range(5),-1))# In numpy, -1 is referring to axis, (In 2D,axis=0 is along column;axis=1 along rows)

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [4]:
import numpy as np
Z=np.array([1])
print(Z**Z,
2 << Z >> 2,
Z <- Z,
1j*Z,
Z/1/1,
Z<Z>Z)

[1] [1] [False] [0.+1.j] [1.] [False]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [3]:
print(np.array(0) / np.array(0),
np.array(0) // np.array(0),
np.array([np.nan]).astype(int).astype(float))

nan 0 [-2.14748365e+09]


C:\Users\Admin PC\AppData\Local\Temp\ipykernel_7328\2861961488.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0),
C:\Users\Admin PC\AppData\Local\Temp\ipykernel_7328\2861961488.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0),


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [15]:
a=np.random.uniform(-30,+30,10)
print(a)

# absolute values of a
b=np.abs(a) 


# ceil([arr]) returns the smallest integer of float value(i.e >= float value)
c=np.ceil(b)  


# copysign(x,y)returns the magnitude of x and sign of y
d=np.copysign(c,a)
print(d)





[ -9.84862223  20.58470928  13.25457538 -29.34899628  22.40316661
   9.43794866  -8.50747194  25.92097134  -4.56285937 -20.78583031]
[-10.  21.  14. -30.  23.  10.  -9.  26.  -5. -21.]


In [16]:
a = np.random.uniform(-30,+30,10) #uniform(-limit,+limit,no. of samples)
b = np.copysign(np.ceil(np.abs(a)),a) # returns the round off values
print(x)
print(y)

[ 20.92496151   2.68945301  29.43884823  25.07662736   2.65347933
  -1.94734274  -5.64736996 -27.90881581 -14.28733087   9.24731906]
[ 21.   3.  30.  26.   3.  -2.  -6. -28. -15.  10.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [17]:
a=np.arange(0,10)
b=np.arange(5,15)
c=np.intersect1d(a,b)
print(c)

[5 6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [19]:
# Allowing warnings by seterr():
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Setting again default:
_ = np.seterr(**defaults)

#Another method using errstate():
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [20]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Admin PC\AppData\Local\Temp\ipykernel_7328\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [26]:
yest = np.datetime64("today","D") - np.timedelta64(1,"D") # Today date -1 day (for getting yesterday) 
today = np.datetime64("today","D")
tomorrow = np.datetime64("today","D") + np.timedelta64(1,"D")
print("Yesterday:",yest)
print("Today:",today)
print("Tommorrow:",tomorrow)

Yesterday: 2023-01-07
Today: 2023-01-08
Tommorrow: 2023-01-09


In [33]:
yest=np.timedelta64(2,"D")
yest

numpy.timedelta64(2,'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [29]:
np.arange("2016-01","2016-02",dtype="datetime64[D]")

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [47]:
A = np.arange(5.0)
B = np.arange(2.0,7.0)
                       # It can add,multiply,divide if two array has same shape 
np.add(A,B,out = B)

np.divide(A,2,out=A)

np.negative(A,out =A)

np.multiply(A,B,out=A)

array([ -0.,  -2.,  -6., -12., -20.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [58]:
a=np.random.uniform(0,100,10) # random.uniform(low,high,size)
print(a)
print(a-a%1) # By modulus method
print(np.floor(a)) # by floor method(round-down method)
print(np.ceil(a)) # by ceil method(round up method)
print(a.astype("int64")) # by astype("int64")
print(np.trunc(a)) #(round towards zero)

[62.48429189 34.63595968  4.40255534 42.32033579 58.36287291 13.26047907
 11.33089751 34.55575171 79.5796909  36.05703809]
[62. 34.  4. 42. 58. 13. 11. 34. 79. 36.]
[62. 34.  4. 42. 58. 13. 11. 34. 79. 36.]
[63. 35.  5. 43. 59. 14. 12. 35. 80. 37.]
[62 34  4 42 58 13 11 34 79 36]
[62. 34.  4. 42. 58. 13. 11. 34. 79. 36.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [76]:
#method1
a = np.ones((5,5))
a = np.arange(5) * a
print(a)

#method2
a2 = np.zeros((5,5))
a2 = np.arange(5) + a2
print(a2)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [79]:
def generate():
    iterable= [x for x in range(10)]
    return iterable
print(np.fromiter(generate(),int))   # np.fromiter(iterables,dtype) same as  np.array(iterable)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [90]:

#numpy.linspace(start,stop,num = np. of samples,endpoint = True,retstep = False,dtype = None)
a=np.linspace(0,1,num = 11,endpoint=False)[1:] 
print(a)                        # Here endpoint= False and [1:] for excluding both

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [81]:
a=np.random.random(10)
a.sort()  # For sorting the array
print(a)

[0.05854222 0.07975916 0.15502068 0.17833112 0.17939631 0.22145856
 0.30604528 0.32981888 0.72108458 0.98979925]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [84]:
a=np.arange(10)
print(np.add.reduce(a)) # Another method is np.sum but slower than this in small matrix


45


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [86]:
A = np.random.randint(0,10,5)
print(A)
B = np.random.randint(0,10,5)
print(B)
#method 1:
print(np.allclose(A,B))
# Method 2:
print(np.array_equal(A,B))

[2 6 2 0 9]
[8 8 9 7 3]
False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [93]:
x = np.zeros(10)
print(x)
x.flags.writeable = False # making array immutable
x[3] = 15

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [10]:
z = np.random.random((10,2))
x,y = z[:,0],z[:,1]  #x,y is cartesian co-ordinates
r= np.sqrt(x**2 + y**2) #r=sq. root of (x^2 + y^2)
angle= np.arctan2(y,x) # angle=tan^-1(y/x)
print(r)
print(angle) # (r,angle) is polar co-ordinates



[0.37109891 0.52932929 0.51215713 1.01933039 0.82616148 0.62993519
 1.04813301 0.63909225 0.87056568 0.62537687]
[0.90181551 0.99359667 0.09563228 1.01419434 0.45403854 0.51485404
 0.97031571 0.78427333 0.88316224 1.47933833]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [119]:
a = np.random.randint(1,10,10)
print(a)
a[a.argmax()]= 0 #converting the max value into zero
print(a)

[3 2 5 6 2 8 1 8 3 1]
[3 2 5 6 2 0 1 8 3 1]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [9]:

'''Structured arrays are ndarrays whose datatype is a composition of simpler datatypes 
organized as a sequence of named fields.'''
import numpy as np
Z = np.zeros((5,5), [('x',float),('y',float)])
print(Z)
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5)) # it returns 2 2d array from 2 1d array
# But here 2 2d array joined as co-ordinates by structured array of z
print(Z)


[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]
[0.   0.25 0.5  0.75 1.  ]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [14]:

X = np.arange(3)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y) # a[ij]=1/(x[ij]-y[ij]) cauchy matrix form
#x[ij]-y[ij] is not done by np.subtract(); It can be done only by np.subtract.outer()
print(C)
print(np.linalg.det(C)) # determinant of square matrix(cauchy matrix) 

[[-2.         -0.66666667 -0.4       ]
 [ 2.         -2.         -0.66666667]
 [ 0.66666667  2.         -2.        ]]
-15.17037037037037


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [16]:
#for integer types
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype))
    print()
    
#for float types
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype))
    print()

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------


Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------


Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------


Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
-----------------------------------------------------------

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [20]:
np.set_printoptions(threshold=np.inf) # threshold = sys.maxsize for numbers displaying all values in array
a=np.zeros((25,25))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [26]:
x = np.arange(100)
y = np.random.uniform(0,100) # random uniform dist variable
index = (np.abs(x-y)).argmin() # argument/index of x close to y variable
print(x[index]) # closest value to a given scalar value

62


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [30]:
x = np.zeros((2,2), [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(x)  # structured array of((positions(x,y)),(colour(r,g,b))

[[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]
 [((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]]


C:\Users\Admin PC\AppData\Local\Temp\ipykernel_14500\1817649221.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  x = np.zeros((2,2), [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [32]:
Z = np.random.random((10,2)) # Here (10,2) is created for displaying result smoothly
print(Z)
X,Y = np.atleast_2d(Z[:,0],Z[:,1]) # To convert into 2-D array with co-ordinates
A = np.sqrt((X-X.T)**2+(Y-Y.T)**2) # distance between two points formula
print(A)

[[0.96621796 0.91115096]
 [0.47295748 0.85137758]
 [0.19017682 0.5096367 ]
 [0.52385556 0.77057069]
 [0.0961354  0.31775081]
 [0.2659062  0.61090486]
 [0.69900238 0.90418354]
 [0.38522654 0.2153835 ]
 [0.96420917 0.10844512]
 [0.81662858 0.39812818]]
[[0.         0.49686895 0.87375829 0.46416302 1.05317017 0.76196081
  0.26730639 0.90644547 0.80270835 0.53438689]
 [0.49686895 0.         0.44356705 0.09550062 0.65326289 0.31732848
  0.23213093 0.6420165  0.89066091 0.56881002]
 [0.87375829 0.44356705 0.         0.42358947 0.21369133 0.12645228
  0.64387162 0.3530288  0.8718261  0.63629864]
 [0.46416302 0.09550062 0.42358947 0.         0.62288873 0.3033662
  0.22029255 0.57223318 0.7951865  0.47373987]
 [1.05317017 0.65326289 0.21369133 0.62288873 0.         0.33876455
  0.84104218 0.30668022 0.8929507  0.72496273]
 [0.76196081 0.31732848 0.12645228 0.3033662  0.33876455 0.
  0.52305324 0.41312769 0.86028648 0.59039738]
 [0.26730639 0.23213093 0.64387162 0.22029255 0.84104218 0.52305324


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [35]:
x= np.arange(25, dtype=np.float32)
x= x.astype(np.int32, copy=False)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [33]:
from io import StringIO # for converting string to string/text file object
# fake file:
s = StringIO("""1, 2, 3, 4, 5\n  
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int) # loading from text file
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\Admin PC\AppData\Local\Temp\ipykernel_14500\3426427472.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [46]:
x = np.arange(4).reshape(2,2)
print(x)

for ind,ele in np.ndenumerate(x):
    print(ind,ele)
    
print()
print("Alternate way of enumerate")
    
for ind in np.ndindex(np.shape(x)): # for accessing the nd index of nd array
    print(ind,x[ind])

[[0 1]
 [2 3]]
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3

Alternate way of enumerate
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [48]:
X,Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
normal= 1/2*(np.sqrt(np.pi * sigma))
Gauss = np.exp(-((D-mu)**2 / (2.0 * sigma**2)))* normal # gaussian distribution
print(Gauss)

[[0.32602467 0.39722541 0.46065623 0.50847573 0.53421597 0.53421597
  0.50847573 0.46065623 0.39722541 0.32602467]
 [0.39722541 0.48397573 0.56125925 0.61952208 0.65088376 0.65088376
  0.61952208 0.56125925 0.48397573 0.39722541]
 [0.46065623 0.56125925 0.65088376 0.71845028 0.75481993 0.75481993
  0.71845028 0.65088376 0.56125925 0.46065623]
 [0.50847573 0.61952208 0.71845028 0.7930307  0.83317578 0.83317578
  0.7930307  0.71845028 0.61952208 0.50847573]
 [0.53421597 0.65088376 0.75481993 0.83317578 0.87535311 0.87535311
  0.83317578 0.75481993 0.65088376 0.53421597]
 [0.53421597 0.65088376 0.75481993 0.83317578 0.87535311 0.87535311
  0.83317578 0.75481993 0.65088376 0.53421597]
 [0.50847573 0.61952208 0.71845028 0.7930307  0.83317578 0.83317578
  0.7930307  0.71845028 0.61952208 0.50847573]
 [0.46065623 0.56125925 0.65088376 0.71845028 0.75481993 0.75481993
  0.71845028 0.65088376 0.56125925 0.46065623]
 [0.39722541 0.48397573 0.56125925 0.61952208 0.65088376 0.65088376
  0.61952208

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [56]:
n = 4
p = 2
Z = np.zeros((n,n))

a = np.random.choice(range(n*n), p, replace=False) # Range to choose,No. of samples
print(a)

np.put(Z, a,5) # To replace elements from specific indexes (np.put(target array,index,new values))
print(Z)

[ 2 12]
[[0. 0. 5. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [5. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [62]:
a=np.random.choice(range(5),10).reshape(5,2)
b=a-a.mean(axis=1,keepdims=True) # keepdims=True for matching the methods with another matrix appropriate
print(b)

[[0 1]
 [3 0]
 [4 1]
 [1 2]
 [4 4]]
[[-0.5  0.5]
 [ 1.5 -1.5]
 [ 1.5 -1.5]
 [-0.5  0.5]
 [ 0.   0. ]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [64]:
a=np.random.randint(1,100,30).reshape(6,5)
b = a[a[:,1].argsort()] # sorting the array by nth column 
print("Original Array")
print(a)
print()
print("Sorted Array ")
print(b)

Original Array
[[ 1 22 25 19 60]
 [30 89 96 86 77]
 [20 88 25 63 47]
 [78  3 33  5 99]
 [69 97 50 35 98]
 [74 14  5 38 93]]

Sorted Array 
[[78  3 33  5 99]
 [74 14  5 38 93]
 [ 1 22 25 19 60]
 [20 88 25 63 47]
 [30 89 96 86 77]
 [69 97 50 35 98]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [76]:
x = np.random.randint(0,3,(5,10))
print((~x.any(axis=0)).any()) # displaying if any column has null values only

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [99]:
x = np.random.uniform(0,1,(3,3))
print(x)
y = 0.65
k = np.abs(x - y).argmin()
print(k)
print(x.flat[k]) # It is used for converting the 2D/3D array into 1d array by index in slice or single index


[[0.49547345 0.58780777 0.9890239 ]
 [0.6525669  0.84619378 0.99813596]
 [0.54636219 0.40590548 0.68906783]]
3
[0.49547345 0.58780777 0.9890239 ]


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [106]:
A = np.random.randint(0,10,3).reshape(3,1)
B = np.random.randint(0,20,3).reshape(1,3)
print(A)
print()
print(B)
print()
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[4]
 [2]
 [0]]

[[13  6 19]]

[[17 10 23]
 [15  8 21]
 [13  6 19]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [6]:
import numpy as np
class Array(np.ndarray):
    def __new__(cls, array, name="no_name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no_name")

x =Array(np.arange(10)) # name is not given, so it takes default name
print (x.name)
y=Array(np.arange(5),"Vishak") # It takes user given name as array name
print(y.name)


no_name
Vishak


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [52]:
Z = np.ones(5) # Array of ones 
I = np.random.randint(0,5,5) # Array to be added
Z=Z + np.bincount(I, minlength=len(Z))
print(X)


[2 4 0 5 6]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [107]:
#I is index,X is weights of bincount
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [74]:
w,h = 20,25 # Width,Height
I = np.random.randint(0,2,(h,w,3),np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2] 
uniq = len(np.unique(F)) # For unique colors
print(uniq)


8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [58]:
A = np.random.randint(0,10,(2,2,2,2))
sum = A.sum(axis=(-2,-1)) # for sum of last two axis
print(sum)

[[28 28]
 [21 12]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [62]:
D = np.random.uniform(0,1,50)
S = np.random.randint(0,10,50)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.47845397 0.13214119 0.25000099 0.55068024 0.37210929 0.60413639
 0.39104504 0.44556203 0.60553279 0.4922223 ]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [60]:
A = np.random.random((5,5))
B = np.random.random((5,5))
c=np.dot(A,B)
print(np.diag(c))

[0.86150023 1.33456673 1.33133161 1.08215441 1.54916105]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [69]:
a=np.array([1,2,3,4,5])
b=np.zeros(len(a)+(len(a)-1)*3)
print(b)
b[::4]=a # For inserting array values in specific index in another array
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [76]:
A = np.random.random((5,5,3))
B = 5*np.ones((5,5))
print(A * B[:,:,None])

[[[2.65389538 1.1021682  2.67979154]
  [3.25817263 2.96760761 1.9853509 ]
  [0.76097217 3.33565793 2.67205344]
  [0.4618687  3.53209957 3.91805587]
  [4.85774331 0.33583491 1.41547154]]

 [[3.04810374 4.17610907 1.65141517]
  [4.7389211  1.62934278 2.21109773]
  [0.75228938 0.61572033 0.7881178 ]
  [1.36086655 2.17509977 2.84305329]
  [1.84834098 3.33280489 1.83744665]]

 [[1.25134583 3.32516895 2.23489497]
  [0.89348876 0.75188927 1.72607091]
  [1.40174746 4.73866243 2.20413645]
  [4.52010564 4.80750308 2.11178119]
  [1.1237381  2.55340941 1.59967647]]

 [[2.57860427 3.94854266 2.44796841]
  [2.60693368 4.33750034 1.45224611]
  [0.05784061 4.64018893 3.28511072]
  [3.90868957 4.25675449 0.79576736]
  [4.46795419 4.2157617  1.65092333]]

 [[4.8623979  0.67313946 3.84083314]
  [2.63239754 0.57050539 1.36605545]
  [1.71742667 2.96259567 2.2813044 ]
  [4.3457843  3.62913231 4.81858657]
  [2.91539597 3.43898402 1.69603055]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [79]:
A = np.arange(20).reshape(4,5)
print(A)
A[[0,2]] = A[[2,0]]
print()
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [15 16 17 18 19]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [11]:
import numpy as np
faces = np.random.randint(0,100,(10,3)) # 10 triangle with their vertices
faces1=faces.repeat(2,axis=1) # For creating the shared points
F = np.roll(faces1,-1,axis=1) # aligning 10 triangle with shared vertices 
# np.roll(array,no. of roll/repetitions,axis=1(row))
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] ) # For converting two columns of array into co,ordinates
G = np.unique(G)
print(G)


[( 7, 58) ( 7, 98) ( 8, 33) ( 8, 56) ( 9, 26) ( 9, 39) (10, 32) (10, 54)
 (10, 65) (10, 85) (11, 52) (11, 63) (13, 25) (13, 65) (13, 75) (25, 65)
 (26, 39) (32, 54) (33, 56) (44, 73) (44, 80) (52, 63) (57, 59) (57, 94)
 (58, 98) (59, 94) (65, 75) (65, 85) (73, 80)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [112]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)),C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [111]:
def moving_average(a, n=3) :
    k = np.cumsum(a, dtype=float)
    k[n:] = k[n:] - k[:-n]
    return k[n - 1:] / n
Z = np.arange(20)
print(Z)
print(moving_average(Z, n=3)) # It gives the moving avaerage of three consecutive numbers

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [27]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    #print(a.size)
    #print(shape)
    strides = (a.itemsize, a.itemsize)
    #print(a)
    #print(strides)
    return stride_tricks.as_strided(a, shape, strides)
Z = rolling(np.arange(20), 3)
print(Z)

[[ 0  1  2]
 [ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]
 [16 17 18]
 [17 18 19]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [115]:
x = np.random.randint(0,2,10)
print(x)
print(np.logical_not(x, out=x)) # It returns contrast boolean to the original array

y = np.random.uniform(-1.0,1.0,10)
print(y)
print(np.negative(y, out=y)) # It returns the negative numbers for positive elements in array and vice verse

[1 1 1 1 0 0 1 1 0 0]
[0 0 0 0 1 1 0 0 1 1]
[-0.87035057 -0.61956396 -0.65833126  0.7307004   0.99644818  0.06050466
 -0.3038224   0.04152829  0.13058382 -0.84790743]
[ 0.87035057  0.61956396  0.65833126 -0.7307004  -0.99644818 -0.06050466
  0.3038224  -0.04152829 -0.13058382  0.84790743]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [34]:
def distance(P0, P1, p):
    T = P1 - P0
    L = np.sqrt(T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))


[ 14.18786022   3.74596967  11.37310603 113.67970359   6.25283445
  42.15183168  26.84808379 123.70617338  45.89575495  69.75686937]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [33]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p])) # Calling the previous problem function


[[ 0.96492028  9.72380967  0.38723868  6.77735513  7.65998161  5.41884819
   7.43235988  8.41536186 12.27562906  5.64482243]
 [ 6.9190535   8.6722984   6.38975864  9.11022195  6.98671317  7.39461016
   6.96954005 12.13202045  8.57658254  1.36401242]
 [ 2.84227747  4.22095847  3.22813175  4.04867391  2.41331863  2.34440169
   2.33408926  7.16822107  5.3994522   1.28205218]
 [ 7.61494649  0.97286276  6.66126599  4.76499881  3.25838691  6.15954192
   3.59553507  2.65275422  4.12226846 10.66058411]
 [ 0.07919276  0.06316215  1.27532844  0.31151988  1.92929455  2.05700386
   2.03563538  3.09924207  1.91449113  2.72271689]
 [ 9.87770616  2.173545   10.02209548  3.81148968  0.32845384  4.94647116
   0.78915419  2.78031422  8.56088049 14.46768197]
 [ 4.29965606  6.28707998  1.53577893  6.63380869  8.23678825  8.4404032
   8.38174135  2.79528919  3.15856802  4.78941673]
 [ 0.95325249  0.96094431  2.65501715  0.38627924  2.74254563  2.22594406
   2.80104488  3.40903897  0.48311869  1.20953809]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [48]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[3 7 8 1 7 5 9 2 2 0]
 [4 3 8 9 2 7 1 4 2 9]
 [0 1 2 0 0 5 0 5 3 9]
 [6 7 5 4 7 1 4 4 0 2]
 [8 9 2 8 3 1 2 4 4 7]
 [8 8 0 4 4 0 9 8 2 1]
 [3 6 0 1 9 5 0 0 7 4]
 [9 5 0 2 0 0 9 5 4 3]
 [8 9 8 3 6 7 4 3 0 9]
 [3 8 3 6 6 0 5 4 2 0]]
[[0 0 0 0 0]
 [0 3 7 8 1]
 [0 4 3 8 9]
 [0 0 1 2 0]
 [0 6 7 5 4]]


C:\Users\Admin PC\AppData\Local\Temp\ipykernel_12132\1159162857.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [51]:
x= np.arange(1,15,dtype=np.int32)
y= stride_tricks.as_strided(x,(11,4),(4,4)) # stride_tricks.as_strided(array,shape to get,strides by itemsize)
print(y)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [63]:
X= np.random.random((10,10))
#print(X)
U, S, VT = np.linalg.svd(X) #Singular value decomposition
rank = np.sum(S > 1e-10) 
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [65]:
x = np.random.randint(0,20,30)
print(x)
print(np.bincount(x).argmax()) # Max count of the array

[ 8  6  7 19 13  0  8  7 15  7 16 14  8 13 16  9  1 17 11  6 12 13  6 16
  8 13 10 19 11  2]
8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [70]:
Z = np.random.randint(0,5,(10,10))
print(Z)
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
print(Z.strides)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)


[[3 2 2 3 2 2 4 0 2 3]
 [3 0 2 0 2 2 3 0 4 3]
 [2 0 0 4 2 4 0 0 3 1]
 [4 1 4 1 4 2 1 4 3 2]
 [1 4 0 0 1 4 4 2 0 2]
 [4 0 0 1 1 2 3 3 2 2]
 [0 1 2 1 4 0 0 3 1 0]
 [1 2 3 4 4 3 3 3 2 4]
 [2 3 2 1 2 2 1 2 3 1]
 [1 2 0 2 0 4 1 3 0 0]]
(40, 4)
[[[[3 2 2]
   [3 0 2]
   [2 0 0]]

  [[2 2 3]
   [0 2 0]
   [0 0 4]]

  [[2 3 2]
   [2 0 2]
   [0 4 2]]

  [[3 2 2]
   [0 2 2]
   [4 2 4]]

  [[2 2 4]
   [2 2 3]
   [2 4 0]]

  [[2 4 0]
   [2 3 0]
   [4 0 0]]

  [[4 0 2]
   [3 0 4]
   [0 0 3]]

  [[0 2 3]
   [0 4 3]
   [0 3 1]]]


 [[[3 0 2]
   [2 0 0]
   [4 1 4]]

  [[0 2 0]
   [0 0 4]
   [1 4 1]]

  [[2 0 2]
   [0 4 2]
   [4 1 4]]

  [[0 2 2]
   [4 2 4]
   [1 4 2]]

  [[2 2 3]
   [2 4 0]
   [4 2 1]]

  [[2 3 0]
   [4 0 0]
   [2 1 4]]

  [[3 0 4]
   [0 0 3]
   [1 4 3]]

  [[0 4 3]
   [0 3 1]
   [4 3 2]]]


 [[[2 0 0]
   [4 1 4]
   [1 4 0]]

  [[0 0 4]
   [1 4 1]
   [4 0 0]]

  [[0 4 2]
   [4 1 4]
   [0 0 1]]

  [[4 2 4]
   [1 4 2]
   [0 1 4]]

  [[2 4 0]
   [4 2 1]
   [1 4 4]]

  [[4 0 0]
   [2 1 4]


#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [74]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric) 

S = symetric(np.random.randint(0,10,(5,5)))
print(S)
S[3,2] = 100
print()
print(S) # Here element of (3,2) is changed and it is reflected in (2,3) also


[[ 2 12  8 15 11]
 [12  1  6  8 10]
 [ 8  6  1 10  7]
 [15  8 10  6  5]
 [11 10  7  5  2]]

[[  2  12   8  15  11]
 [ 12   1   6   8  10]
 [  8   6   1 100   7]
 [ 15   8 100   6   5]
 [ 11  10   7   5   2]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [75]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
print(M)
print()
print(V)
print()
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]

[[[1.]
  

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [81]:
Z = np.ones((16,16))
print(Z)
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], 4), axis=1)
print(S)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [83]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [86]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(Z)
# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[3812 2996 8621 ... 9849 4799 4608]
[9995 9996 9997 9998 9999]
[9997 9999 9998 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [87]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [112]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
print(Z)
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3', # Names 
                               formats = 'S8, f8, i8') # String,float,integer
print(R)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]
[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [91]:
Z = np.random.randint(5e7)

%timeit np.power(Z,3)
%timeit Z*Z*Z
%timeit np.einsum('i,i,i->i',Z,Z,Z)

2.86 µs ± 444 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
325 ns ± 46.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


ValueError: einstein sum subscripts string contains too many subscripts for operand 0

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [111]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0] 
print(rows)


[2 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [108]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1) # Checing for equality
print()
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print()
print(U)


[[4 0 0]
 [0 1 0]
 [4 4 1]
 [2 3 2]
 [2 4 0]
 [3 2 1]
 [2 4 3]
 [1 0 3]
 [2 4 2]
 [3 4 1]]

[[4 0 0]
 [0 1 0]
 [4 4 1]
 [2 3 2]
 [2 4 0]
 [3 2 1]
 [2 4 3]
 [1 0 3]
 [2 4 2]
 [3 4 1]]

[[4 0 0]
 [0 1 0]
 [4 4 1]
 [2 3 2]
 [2 4 0]
 [3 2 1]
 [2 4 3]
 [1 0 3]
 [2 4 2]
 [3 4 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [95]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))  # Converts the integer into binary with newaxis form

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [96]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [97]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

print(np.einsum('i->', A))      # np.sum(A)
print(np.einsum('i,i->i', A, B)) # A * B
print(np.einsum('i,i', A, B))    # np.inner(A, B)
print(np.einsum('i,j->ij', A, B))   # np.outer(A, B)

5.566454612325293
[0.65031982 0.02284042 0.24730061 0.50474817 0.16335626 0.37832322
 0.06652805 0.57102064 0.63518996 0.14163667]
3.381263828342554
[[0.65031982 0.08946756 0.70553458 0.50802674 0.27888749 0.44890953
  0.38807104 0.75409856 0.5624385  0.38339635]
 [0.16602198 0.02284042 0.18011791 0.12969558 0.07119797 0.11460338
  0.09907175 0.19251594 0.14358651 0.09787833]
 [0.227947   0.03135974 0.24730061 0.17807111 0.09775431 0.15734962
  0.13602481 0.26432303 0.19714326 0.13438626]
 [0.64612296 0.08889017 0.70098139 0.50474817 0.27708768 0.44601247
  0.38556661 0.74923196 0.55880879 0.38092209]
 [0.38091996 0.05240495 0.4132616  0.29757286 0.16335626 0.26294539
  0.2273097  0.44170759 0.32944414 0.22457154]
 [0.54806386 0.07539972 0.59459668 0.42814487 0.23503536 0.37832322
  0.32705094 0.63552449 0.47400096 0.3231113 ]
 [0.11148605 0.01533766 0.12095167 0.08709237 0.04781042 0.07695775
  0.06652805 0.12927712 0.09642032 0.06572665]
 [0.492437   0.06774687 0.53424689 0.38468944 

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [99]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [100]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [101]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.24120873  0.16216292]
